### PR TITLE
feature: notify deploys to spine

### PR DESCRIPTION
**Pull request by tux4**

### CODE REVIEW

**Comment by chollier** [comment]
@tux4 could you make the SPINE_ENDPOINT an env variable ? I'd rather not leak it on a public repo

**Comment by tux4** [comment]
@chollier Added SPINE_ENDPOINT to env variables: https://github.com/quri/deployments-notifier/pull/1/commits/4b93df476e2ce5a5c504d09f8acb7296f268392a . Also update approvals with production values: https://github.com/quri/approvals/pull/222/commits/f1393bdb553f3074845c40b36ff543c3b13a394c

**Comment by chollier** [comment]
LGTM

**Comment by chollier** [comment]
@tux4 I'll let you merge when you think it should be

**Pull request merged**
